### ISSUE TITLE
Support spark2.0.0

### ISSUE THREAD

**Issue by zainryan** [broadinstitute/gatk#2073]
Last week, spark 2.0.0 is formally released. However, when I tested gatk4 on spark2.0.0, I found they were incompatible.

It seems that the interface isn't match. The error log looks like below.

Exception in thread "main" java.lang.NoSuchMethodError: scala.collection.Seq.aggregate(Ljava/lang/Object;Lscala/Function2;Lscala/Function2;)Ljava/lang/Object;
    at org.bdgenomics.adam.models.NonoverlappingRegions.mergeRegions(NonoverlappingRegions.scala:75)
    at org.bdgenomics.adam.models.NonoverlappingRegions.<init>(NonoverlappingRegions.scala:55)
    at org.bdgenomics.adam.models.NonoverlappingRegions$.apply(NonoverlappingRegions.scala:169)
    at org.bdgenomics.adam.util.TwoBitRecord$.apply(TwoBitFile.scala:193)
    at org.bdgenomics.adam.util.TwoBitFile$$anonfun$6.apply(TwoBitFile.scala:70)
    at org.bdgenomics.adam.util.TwoBitFile$$anonfun$6.apply(TwoBitFile.scala:70)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:221)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
    at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:428)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at org.bdgenomics.adam.util.TwoBitFile.<init>(TwoBitFile.scala:70)
    at org.broadinstitute.hellbender.engine.spark.datasources.ReferenceTwoBitSource.<init>(ReferenceTwoBitSource.java:43)
    at org.broadinstitute.hellbender.engine.datasources.ReferenceMultiSource.<init>(ReferenceMultiSource.java:41)
    at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeReference(GATKSparkTool.java:353)
    at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.initializeToolInputs(GATKSparkTool.java:320)
    at org.broadinstitute.hellbender.engine.spark.GATKSparkTool.runPipeline(GATKSparkTool.java:311)
    at org.broadinstitute.hellbender.engine.spark.SparkCommandLineProgram.doWork(SparkCommandLineProgram.java:38)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:108)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:166)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:185)
    at org.broadinstitute.hellbender.Main.instanceMain(Main.java:76)
    at org.broadinstitute.hellbender.Main.main(Main.java:92)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:729)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:185)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:210)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:124)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
16/08/02 20:24:09 INFO util.ShutdownHookManager: Shutdown hook called
16/08/02 20:24:09 INFO util.ShutdownHookManager: Deleting directory /ssd_hdfs2/spark_tmp/spark-42d0223f-b492-43e3-a6fa-d4edd98b2324

**Comment by droazen** [comment]
@tomwhite Could you have a look?

**Comment by tomwhite** [comment]
I've created a branch for testing here: https://github.com/broadinstitute/gatk/tree/tw_spark2.

Note that we can't upgrade until the CDH cluster is upgraded to Spark 2. Also, ADAM format support is disabled until ADAM works with Spark 2 (slated for ADAM 0.20.0: https://github.com/bigdatagenomics/adam/issues/1021)

**Comment by fnothaft** [comment]
Hi @tomwhite; thanks for pinging this upstream on https://github.com/bigdatagenomics/adam/issues/1093. As per my comment there, I believe that it's only the various RDD transforms in ADAM that are impacted by the Spark 2.0.0 shift. I believe that the issue that was reported here is a Scala 2.10 vs. 2.11 issue. The GATK build points at [ADAM 0.18.0 built for Scala 2.10](https://github.com/broadinstitute/gatk/blob/master/build.gradle#L128). If you shifted said dependency to `compile('org.bdgenomics.adam:adam-core_2.11:0.18.0')`, I believe the error above would disappear. However, this is just conjecture; I haven't tested it.

**Comment by tomwhite** [comment]
Thanks for the suggestion @fnothaft. Unfortunately, switching to Scala 2.11 didn't help as I still get a compile error due to the logging change in Spark 2:

```
/Users/tom/workspace/gatk/src/main/java/org/broadinstitute/hellbender/utils/read/GATKReadToBDGAlignmentRecordConverter.java:38: error: cannot access Logging
        return converter.convert(gatkRead.convertToSAMRecord(header), dict, readGroups);
```

I get that with `org.bdgenomics.adam:adam-core_2.11:0.19.0` too.

**Comment by heuermh** [comment]
Per https://github.com/bigdatagenomics/adam/pull/1123 we're planning on releasing separate Spark 1.x and Spark 2.x artifacts with the next ADAM version (0.20.0).

E.g.
```
org.bdgenomics.adam:adam-core_2.10:0.20.0
org.bdgenomics.adam:adam-core-spark2_2.10:0.20.0
```

**Comment by tomwhite** [comment]
I now have a working PR here: https://github.com/broadinstitute/gatk/pull/2220

One data point: I ran MarkDuplicates on a cluster and with Spark 2 it ran in 6.32 minutes, compared to 11.14 minutes on the same cluster. Quite an improvement!

**Comment by tomwhite** [comment]
Fixed in #2220.

**Comment by lbergelson** [comment]
@tomwhite I'm still seeing this issue on dataproc.  It looks like dataproc uses spark with scala 11. 

```
Using Scala version 2.11.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_102)
```

If I rebuild gatk with spark 2.11 then it goes away.  I think we should update to spark 2.11 as the default since dataproc is our primary environment that we target.
