### ISSUE TITLE
[Bug Report] CNNScoreVariants AttributeError: module 'keras.backend' has no attribute 'clear_session'

### ISSUE THREAD

**Issue by TearsWillFall** [broadinstitute/gatk#7250]
### Affected tool(s) or class(es)

CNNScoreVariants

### Affected version(s)
- [x] Latest master branch as of [12/05/2021]. Same issue for an older master branch in v4.1.9.

### Description

**Issue with vqsr_cnn package in Conda environment.
AttributeError: module 'keras.backend' has no attribute 'clear_session'**

> Using GATK jar /lustre/home/regmova/tools/gatk/build/libs/gatk-package-4.2.0.0-19-ge60cdf8-SNAPSHOT-local.jar
>
> Running:
>     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /lustre/home/regmova/tools/gatk/build 
>/libs/gatk-package-4.2.0.0-19-ge60cdf8-SNAPSHOT-local.jar CNNScoreVariants -V TR017.GL.vcf.gz -R /home/regmova
>/Scratch/RefGenome/hs37d5.fa -O TR017.CNNscored.vcf
  10:46:04.904 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/lustre/home/regmova/tools/gatk/build/libs/gatk-package-4.2.0.0-19-ge60cdf8-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_compression.so
  May 12, 2021 10:46:05 AM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
  INFO: Failed to detect whether we are running on Google Compute Engine.
  10:46:05.152 INFO  CNNScoreVariants - ------------------------------------------------------------
  10:46:05.152 INFO  CNNScoreVariants - The Genome Analysis Toolkit (GATK) v4.2.0.0-19-ge60cdf8-SNAPSHOT
  10:46:05.152 INFO  CNNScoreVariants - For support and documentation go to https://software.broadinstitute.org/gatk/
  10:46:05.152 INFO  CNNScoreVariants - Java runtime: Java HotSpot(TM) 64-Bit Server VM v1.8.0_92-b14
  10:46:05.152 INFO  CNNScoreVariants - Start Date/Time: 12 May 2021 10:46:04 BST
  10:46:05.152 INFO  CNNScoreVariants - ------------------------------------------------------------
  10:46:05.152 INFO  CNNScoreVariants - ------------------------------------------------------------
  10:46:05.153 INFO  CNNScoreVariants - HTSJDK Version: 2.24.1
  10:46:05.153 INFO  CNNScoreVariants - Picard Version: 2.25.0
  10:46:05.153 INFO  CNNScoreVariants - Built for Spark Version: 2.4.5
  10:46:05.153 INFO  CNNScoreVariants - HTSJDK Defaults.COMPRESSION_LEVEL : 2
  10:46:05.153 INFO  CNNScoreVariants - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
  10:46:05.153 INFO  CNNScoreVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
  10:46:05.153 INFO  CNNScoreVariants - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
  10:46:05.153 INFO  CNNScoreVariants - Deflater: IntelDeflater
  10:46:05.153 INFO  CNNScoreVariants - Inflater: IntelInflater
  10:46:05.153 INFO  CNNScoreVariants - GCS max retries/reopens: 20
  10:46:05.153 INFO  CNNScoreVariants - Requester pays: disabled
  10:46:05.153 INFO  CNNScoreVariants - Initializing engine
  10:46:05.598 INFO  FeatureManager - Using codec VCFCodec to read file file:///lustre/scratch/scratch/regmova/tmp/TEST_DATA/TR017_GERMLINE_VARIANTS/TR017.GL.vcf.gz
  10:46:05.638 INFO  CNNScoreVariants - Done initializing engine
  10:46:05.639 INFO  NativeLibraryLoader - Loading libgkl_utils.so from jar:file:/lustre/home/regmova/tools/gatk/build/libs/gatk-package-4.2.0.0-19-ge60cdf8-SNAPSHOT-local.jar!/com/intel/gkl/native/libgkl_utils.so
  10:46:35.436 INFO  CNNScoreVariants - Using key:CNN_1D for CNN architecture:/tmp/1d_cnn_mix_train_full_bn.8208762367402959162.json and weights:/tmp/1d_cnn_mix_train_full_bn.2787226329292768726.hd5
  10:46:35.438 INFO  CNNScoreVariants - Done scoring variants with CNN.
  10:46:35.438 INFO  CNNScoreVariants - Shutting down engine
  [12 May 2021 10:46:35 BST] org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants done. Elapsed time: 0.51 minutes.
  Runtime.totalMemory()=2132279296
  org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: A nack was received from the Python process (most likely caused by a raised exception caused by): nkm received

```
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/regmova/miniconda3/envs/gatk/lib/python3.6/site-packages/vqsr_cnn/vqsr_cnn/models.py", line 22, in start_session_get_args_and_model
      K.clear_session()


AttributeError: module 'keras.backend' has no attribute 'clear_session'
	at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.waitForAck(StreamingPythonScriptExecutor.java:222)
	at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.sendSynchronousCommand(StreamingPythonScriptExecutor.java:183)
    at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.initializePythonArgsAndModel(CNNScoreVariants.java:557)
    at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.onTraversalStart(CNNScoreVariants.java:317)
    at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1056)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
    at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
    at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
    at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
    at org.broadinstitute.hellbender.Main.main(Main.java:289) 
```

#### Steps to reproduce
`conda activate gatk; gatk CNNScoreVariants -V VCF.vcf.gz -R reference.fa -O VCF.CNNscored.vcf `

#### Expected behaviour
CNNScoreVariants should generate an annotated VCF

#### Actual behavior
CNNScoreVariants crashes

#### What I tried
I ran into this issue with an older build based on v4.1.9. I upgraded to v4.2.0, removed and built the Conda environment again, but the issue persisted. 

----

**Comment by TearsWillFall** [comment]
A fix I found for this issue is to modify `start_session_get_args_and_model` function in models.py from this:

```
def start_session_get_args_and_model(intra_ops, inter_ops, semantics_json, weights_hd5=None, tensor_type=None):
    K.clear_session()
    K.get_session().close()
    cfg = K.tf.ConfigProto(intra_op_parallelism_threads=intra_ops, inter_op_parallelism_threads=inter_ops)
    cfg.gpu_options.allow_growth = True
    K.set_session(K.tf.Session(config=cfg))
    return args_and_model_from_semantics(semantics_json, weights_hd5, tensor_type)

```


To this:

```
import tensorflow as tf

def start_session_get_args_and_model(intra_ops, inter_ops, semantics_json, weights_hd5=None, tensor_type=None):
    tf.keras.backend.clear_session()
    tf.keras.backend.get_session().close()
    cfg = tf.ConfigProto(intra_op_parallelism_threads=intra_ops, inter_op_parallelism_threads=inter_ops)
    cfg.gpu_options.allow_growth = True
    tf.keras.backend.set_session(tf.Session(config=cfg))
    return args_and_model_from_semantics(semantics_json, weights_hd5, tensor_type)

```

**Comment by droazen** [comment]
@TearsWillFall To help us diagnose this issue, could you please try running the same `CNNScoreVariants` command in our official 4.2 docker image in dockerhub (https://hub.docker.com/r/broadinstitute/gatk/), and report whether you get the same error?

**Comment by TearsWillFall** [comment]
> @TearsWillFall To help us diagnose this issue, could you please try running the same `CNNScoreVariants` command in our official 4.2 docker image in dockerhub (https://hub.docker.com/r/broadinstitute/gatk/), and report whether you get the same error?

Just to confirm and clarify. The same command works fine on a 4.2.0 docker image built on Singularity. 
However, it doesn't seem to work, when I either:

A) Download the zip/tar and build the conda environment as per Requirements section instructions using `conda env create -f gatkcondaenv.yml `
B) Clone the master repo build gatk and use `./gradlew localDevCondaEnv` to build the conda env.

In both cases, I seem to get the error above mentioned.

**Comment by LRFreeborn** [comment]
@droazen I'm getting a similar error (see below), but the 'import tensorflow as tf' didn't work for me. Any suggestions? I installed gatk 4.2.2 from the zip file and built the python environment with miniconda 

Error log:
org.broadinstitute.hellbender.utils.python.PythonScriptExecutorException: A nack was received from the Python process (most likely caused by a raised exception caused by): nkm received

: Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "/N/soft/rhel7/gatk/4.2.2.0/lib/python3.6/site-packages/vqsr_cnn/vqsr_cnn/models.py", line 22, in start_session_get_args_and_model
    K.clear_session()
   File "/N/soft/rhel7/gatk/4.2.2.0/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 96, in clear_session
    tf.reset_default_graph()
 AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'

        at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.waitForAck(StreamingPythonScriptExecutor.java:222)
        at org.broadinstitute.hellbender.utils.python.StreamingPythonScriptExecutor.sendSynchronousCommand(StreamingPythonScriptExecutor.java:183)
        at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.initializePythonArgsAndModel(CNNScoreVariants.java:557)
        at org.broadinstitute.hellbender.tools.walkers.vqsr.CNNScoreVariants.onTraversalStart(CNNScoreVariants.java:317)
        at org.broadinstitute.hellbender.engine.GATKTool.doWork(GATKTool.java:1083)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.runTool(CommandLineProgram.java:140)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMainPostParseArgs(CommandLineProgram.java:192)
        at org.broadinstitute.hellbender.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:211)
        at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:160)
        at org.broadinstitute.hellbender.Main.mainEntry(Main.java:203)
        at org.broadinstitute.hellbender.Main.main(Main.java:289)

**Comment by LRFreeborn** [comment]
@cmnbroad small update: i tried creating the conda environment from a fresh miniconda install and got the same error I included in my above post.
